### ISSUE TITLE
Histogram: Hardcoded implementation

### ISSUE THREAD

**Issue by PCXDME** [Rostlab/JS18_ProjectB_Group4#1]

**Comment by shabnamsadegh** [comment]
I created a folder in the google drive. which contains a testable UI for the hardcodes.(Histograms.html)

**Comment by syxolk** [comment]
Why would you push it to GDrive and not Git?

**Comment by shabnamsadegh** [comment]
Good question. :)
I did not know how to break my code to proposed architecture. But still I could upload there.

**Comment by PCXDME** [comment]
@syxolk Git should contain codes that are close to production code as much as possible.
The implementation is just something like what we do in JSFiddle (trying functionality).
We will put in Git on milestone 3 (Integrate charts method with API).
We are figuring out good design structure/architecture of the code to be integrate to project.

**Comment by syxolk** [comment]
I see, do as you like.

**Comment by Phibedy** [comment]
@PCXDME I thought that this is one reason for using branches. Now I have to go and look for some usb flash drivers. You never stop learning :dancer:
