### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by fhnaseer** [Rostlab/JS18_ProjectB_Group4#13]

**Comment by syxolk** [comment]
Hey, there are currently two show stoppers here to make CI work.
- `npm test` fails because you no longer use swagger but you call it there.
- Why did you put everything in a subfolder? It's not actually a big issue but I don't see the reason for it.

**Comment by fhnaseer** [comment]
I updated the code and sent you review. It will fix the test issue,
Subfolder. Earlier we were thinking to have separate app for frontend and thought to have two folders (backend = plot-editor, frontend = plot-viewer). But later we dropped that idea,

**Comment by syxolk** [comment]
So you can move everything one folder up?

**Comment by fhnaseer** [comment]
Yeah sure, i just created the pull request,

**Comment by syxolk** [comment]
Added `.travis.yml` and enabled travis successfully.
