### ISSUE TITLE
Histogram: Parameterize implementation

### ISSUE THREAD

**Issue by PCXDME** [Rostlab/JS18_ProjectB_Group4#2]

**Comment by shabnamsadegh** [comment]
In histograms.html there is a parameterized function that supports all variation of changes in bins.

1. only set number of bins
2. only set size of bin
3. without setting number or size, it will use automatic sizing(default sizing)
3. only set start and uses max of x as end
4. only set end and uses min of x as start
5. any combination of 1 to 4

The code structure should be combined with others. there are redundant codes.

**Comment by PCXDME** [comment]
I would recommend to use separate functions for each functionality as it provides less coupling.
Imagine that the NLP system have to call the function to make changes.
If one day, we want to add some parameter to this function, we would have to change function call in many parts of NLP system.
Another advantages are that it is easier for testing, documentation and less error prone.

**Comment by shabnamsadegh** [comment]
Yes I totally agree with you. However in this case the attributes where coupled. It means depends on start and end, calculation of number and size of bin  is different. 

There is an attribute xbin which is an object with 3 attrs. And the behaviour also was coupled with autobinx. 

So actually it is still one attr per function as you said. 

when we talk next time to combine codes. If we anyway agree it is better to decouple, I can change it.
